---
# Disabled for Workshop use, but can be used for other installations
# ah_repository_certified:
#   token: ""
#   url: 'https://console.redhat.com/api/automation-hub/'
#   auth_url: 'https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token'
#   wait: true

ah_repository_community:
  url: https://galaxy.ansible.com/api/
  # Note: We want to filter what gets pulled from galaxy
  # for reasons of space, security, and quality.
  # For posterity I am mentioning here that you cannot use roles with
  # private automation hub, only collections
  requirements:
    - infra.aap_utilities
    - infra.ee_utilities
    - containers.podman
    - awx.awx
    - community.general
  wait: true

ah_repository_certified:
  token: "{{ cloud_token }}"
  #url: 'https://console.redhat.com/api/automation-hub/'
  url: 'https://console.redhat.com/api/automation-hub/content/published/'
  auth_url: 'https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token'
  wait: true
...