---
controller_execution_environments:
  - name: "supported"
    image: hub-student1.w2bmh.example.opentlc.com/ee-supported-rhel8
    pull: "always"
    credential: "cr_ah"
  - name: "minimal"
    image: hub-student1.w2bmh.example.opentlc.com/ee-minimal-rhel8
    pull: "always"
    credential: "cr_ah"
  - name: "old_29_ee"
    image: hub-student1.w2bmh.example.opentlc.com/ee-29-rhel8
    pull: "always"
    credential: "cr_ah"
...
