---
controller_projects:
  - name: config_as_code
    description: execution environments configurations
    organization: config_as_code
    scm_branch: homelab_test
    scm_clean: 'yes'
    scm_delete_on_update: 'no'
    scm_type: git
    scm_update_on_launch: 'yes'
    scm_url: https://github.com/benblasco/aap-as-code.git
    credential: git

  - name: insights_project
    description: Red Hat Insights project
    organization: config_as_code
    scm_type: insights
    credential: insights_credential
...
